/* eslint-disable @typescript-eslint/no-require-imports */
'use strict';

const { v4: uuidv4 } = require('uuid');

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    const now = new Date();

    const groups = [
      {
        id: uuidv4(),
        name: 'Unity Circle',
        description: 'Building wealth together.',
        holder: 'admin',
        targetMemberCount: 10,
        contributionAmount: 100,
        payoutDay: 'monday',
        payoutOrder: 'random',
        frequency: 'weekly',
        isPublic: true,
        repeat: true,
        startImmediately: true,
        defaultCurrency: 'USD',
        createdAt: now,
        updatedAt: now,
        ownerId: '01a50a31-81d5-4eae-84e6-4a44daec263e',
      },
      {
        id: uuidv4(),
        name: 'Dream Savers',
        description: 'Turn dreams into plans.',
        holder: 'admin',
        targetMemberCount: 8,
        contributionAmount: 50,
        payoutDay: 'friday',
        payoutOrder: 'first-come-first-serve',
        frequency: 'bi-weekly',
        isPublic: false,
        repeat: true,
        startImmediately: false,
        defaultCurrency: 'GBP',
        createdAt: now,
        updatedAt: now,
        ownerId: '1ba3c29a-d721-457e-906c-e39164eef4ff',
      },
      {
        id: uuidv4(),
        name: 'Golden Nest',
        description: 'Prepare for golden years.',
        holder: 'admin',
        targetMemberCount: 6,
        contributionAmount: 200,
        payoutDay: 'wednesday',
        payoutOrder: 'random',
        frequency: 'monthly',
        isPublic: true,
        repeat: false,
        startImmediately: true,
        defaultCurrency: 'KES',
        createdAt: now,
        updatedAt: now,
        ownerId: '9948d2d6-0fa5-402e-a281-66275be44f3a',
      },
      {
        id: uuidv4(),
        name: 'Bright Future Fund',
        description: 'Invest in tomorrow.',
        holder: 'member',
        targetMemberCount: 7,
        contributionAmount: 150,
        payoutDay: 'tuesday',
        payoutOrder: 'first-come-first-serve',
        frequency: 'weekly',
        isPublic: false,
        repeat: true,
        startImmediately: true,
        defaultCurrency: 'EUR',
        createdAt: now,
        updatedAt: now,
        ownerId: '3cd4a2cd-6c05-4ae1-ab42-ef3c5c37deac',
      },
      {
        id: uuidv4(),
        name: 'Fast Payouts',
        description: 'Quick rotation system.',
        holder: 'admin',
        targetMemberCount: 5,
        contributionAmount: 80,
        payoutDay: 'saturday',
        payoutOrder: 'random',
        frequency: 'daily',
        isPublic: true,
        repeat: true,
        startImmediately: false,
        defaultCurrency: 'NGN',
        createdAt: now,
        updatedAt: now,
        ownerId: '01a50a31-81d5-4eae-84e6-4a44daec263e',
      },
      {
        id: uuidv4(),
        name: 'Prosper Circle',
        description: 'Grow together.',
        holder: 'admin',
        targetMemberCount: 12,
        contributionAmount: 120,
        payoutDay: 'sunday',
        payoutOrder: 'first-come-first-serve',
        frequency: 'monthly',
        isPublic: false,
        repeat: false,
        startImmediately: true,
        defaultCurrency: 'CNY',
        createdAt: now,
        updatedAt: now,
        ownerId: '1ba3c29a-d721-457e-906c-e39164eef4ff',
      },
      {
        id: uuidv4(),
        name: 'Rise Together',
        description: 'Support each other financially.',
        holder: 'admin',
        targetMemberCount: 9,
        contributionAmount: 90,
        payoutDay: 'thursday',
        payoutOrder: 'random',
        frequency: 'weekly',
        isPublic: true,
        repeat: true,
        startImmediately: false,
        defaultCurrency: 'INR',
        createdAt: now,
        updatedAt: now,
        ownerId: '9948d2d6-0fa5-402e-a281-66275be44f3a',
      },
      {
        id: uuidv4(),
        name: 'Momentum Loop',
        description: 'Cash flow made easy.',
        holder: 'admin',
        targetMemberCount: 6,
        contributionAmount: 60,
        payoutDay: 'friday',
        payoutOrder: 'first-come-first-serve',
        frequency: 'bi-weekly',
        isPublic: false,
        repeat: true,
        startImmediately: true,
        defaultCurrency: 'USD',
        createdAt: now,
        updatedAt: now,
        ownerId: 'a876ab28-83c1-4bd5-bee9-c2d2cf1a07b8',
      },
      {
        id: uuidv4(),
        name: 'Chama Network',
        description: 'Community-based funding.',
        holder: 'admin',
        targetMemberCount: 11,
        contributionAmount: 100,
        payoutDay: 'monday',
        payoutOrder: 'random',
        frequency: 'monthly',
        isPublic: true,
        repeat: true,
        startImmediately: true,
        defaultCurrency: 'KES',
        createdAt: now,
        updatedAt: now,
        ownerId: 'aa1ee486-7b44-4604-bdc6-69ad680a2dbd',
      },
      {
        id: uuidv4(),
        name: 'Aspire League',
        description: 'Fund your aspirations.',
        holder: 'admin',
        targetMemberCount: 8,
        contributionAmount: 75,
        payoutDay: 'tuesday',
        payoutOrder: 'first-come-first-serve',
        frequency: 'weekly',
        isPublic: false,
        repeat: true,
        startImmediately: false,
        defaultCurrency: 'GBP',
        createdAt: now,
        updatedAt: now,
        ownerId: '1ba3c29a-d721-457e-906c-e39164eef4ff',
      },
      {
        id: uuidv4(),
        name: 'Zen Circle',
        description: 'Minimalist saving style.',
        holder: 'member',
        targetMemberCount: 4,
        contributionAmount: 40,
        payoutDay: 'wednesday',
        payoutOrder: 'random',
        frequency: 'bi-weekly',
        isPublic: true,
        repeat: true,
        startImmediately: true,
        defaultCurrency: 'EUR',
        createdAt: now,
        updatedAt: now,
        ownerId: '3cd4a2cd-6c05-4ae1-ab42-ef3c5c37deac',
      },
      {
        id: uuidv4(),
        name: 'Wealth Club',
        description: 'Build lasting legacy.',
        holder: 'admin',
        targetMemberCount: 15,
        contributionAmount: 300,
        payoutDay: 'thursday',
        payoutOrder: 'first-come-first-serve',
        frequency: 'monthly',
        isPublic: false,
        repeat: false,
        startImmediately: false,
        defaultCurrency: 'USD',
        createdAt: now,
        updatedAt: now,
        ownerId: '9948d2d6-0fa5-402e-a281-66275be44f3a',
      },
      {
        id: uuidv4(),
        name: 'Circle Boost',
        description: 'Boost each other forward.',
        holder: 'admin',
        targetMemberCount: 9,
        contributionAmount: 90,
        payoutDay: 'friday',
        payoutOrder: 'random',
        frequency: 'weekly',
        isPublic: true,
        repeat: true,
        startImmediately: true,
        defaultCurrency: 'INR',
        createdAt: now,
        updatedAt: now,
        ownerId: '01a50a31-81d5-4eae-84e6-4a44daec263e',
      },
      {
        id: uuidv4(),
        name: 'Monthly Move',
        description: 'Structured monthly support.',
        holder: 'member',
        targetMemberCount: 10,
        contributionAmount: 130,
        payoutDay: 'monday',
        payoutOrder: 'first-come-first-serve',
        frequency: 'monthly',
        isPublic: false,
        repeat: false,
        startImmediately: true,
        defaultCurrency: 'NGN',
        createdAt: now,
        updatedAt: now,
        ownerId: 'a876ab28-83c1-4bd5-bee9-c2d2cf1a07b8',
      },
      {
        id: uuidv4(),
        name: 'Helping Hands',
        description: 'We lift each other.',
        holder: 'admin',
        targetMemberCount: 7,
        contributionAmount: 110,
        payoutDay: 'saturday',
        payoutOrder: 'random',
        frequency: 'weekly',
        isPublic: true,
        repeat: true,
        startImmediately: false,
        defaultCurrency: 'CNY',
        createdAt: now,
        updatedAt: now,
        ownerId: 'aa1ee486-7b44-4604-bdc6-69ad680a2dbd',
      },
    ];

    await queryInterface.bulkInsert('groups', groups, {});
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('groups', null, {});
  },
};
