/* eslint-disable @typescript-eslint/no-require-imports */
'use strict';

const argon2 = require('argon2');
const { v4: uuidv4 } = require('uuid');

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    const hashedPassword = await argon2.hash('Password123!');

    const users = [
      {
        id: uuidv4(),
        username: 'emma_johnson',
        firstName: 'Emma',
        lastName: 'Johnson',
        phoneNumber: '+14155550123',
        terms_of_service: true,
        password: hashedPassword,
        provider: 'credentials',
        country: 'United States',
        phone_verified: true,
        joinedAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        username: 'liam_nguyen',
        firstName: 'Liam',
        lastName: 'Nguyen',
        phoneNumber: '+447911123456',
        terms_of_service: true,
        password: hashedPassword,
        provider: 'credentials',
        country: 'United Kingdom',
        phone_verified: true,
        joinedAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        username: 'ava_kumar',
        firstName: 'Ava',
        lastName: 'Kumar',
        phoneNumber: '+918123456789',
        terms_of_service: true,
        password: hashedPassword,
        provider: 'credentials',
        country: 'India',
        phone_verified: true,
        joinedAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        username: 'noah_mwangi',
        firstName: 'Noah',
        lastName: 'Mwangi',
        phoneNumber: '+254712345678',
        terms_of_service: true,
        password: hashedPassword,
        provider: 'credentials',
        country: 'Kenya',
        phone_verified: true,
        joinedAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        username: 'sophia_mueller',
        firstName: 'Sophia',
        lastName: 'Müller',
        phoneNumber: '+4915123456789',
        terms_of_service: true,
        password: hashedPassword,
        provider: 'credentials',
        country: 'Germany',
        phone_verified: true,
        joinedAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        username: 'lucas_garcia',
        firstName: 'Lucas',
        lastName: 'Garcia',
        phoneNumber: '+5511987654321',
        terms_of_service: true,
        password: hashedPassword,
        provider: 'credentials',
        country: 'Brazil',
        phone_verified: true,
        joinedAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        username: 'isabella_chen',
        firstName: 'Isabella',
        lastName: 'Chen',
        phoneNumber: '+8613800138000',
        terms_of_service: true,
        password: hashedPassword,
        provider: 'credentials',
        country: 'China',
        phone_verified: true,
        joinedAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        username: 'ethan_dubois',
        firstName: 'Ethan',
        lastName: 'Dubois',
        phoneNumber: '+33612345678',
        terms_of_service: true,
        password: hashedPassword,
        provider: 'credentials',
        country: 'France',
        phone_verified: true,
        joinedAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        username: 'mia_hassan',
        firstName: 'Mia',
        lastName: 'Hassan',
        phoneNumber: '+971501234567',
        terms_of_service: true,
        password: hashedPassword,
        provider: 'credentials',
        country: 'United Arab Emirates',
        phone_verified: true,
        joinedAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        username: 'james_okoro',
        firstName: 'James',
        lastName: 'Okoro',
        phoneNumber: '+2348012345678',
        terms_of_service: true,
        password: hashedPassword,
        provider: 'credentials',
        country: 'Nigeria',
        phone_verified: true,
        joinedAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    await queryInterface.bulkInsert('users', users, {});
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('users', null, {});
  },
};
