/* eslint-disable @typescript-eslint/no-require-imports */
'use strict';

const { v4: uuidv4 } = require('uuid');

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    const now = new Date();

    const groups = [
      {
        id: uuidv4(),
        name: 'Unity Circle',
        description: 'Building wealth together.',
        holder: 'admin',
        targetMemberCount: 10,
        contributionAmount: 100,
        payoutDay: 'monday',
        payoutOrder: 'random',
        frequency: 'weekly',
        isPublic: true,
        repeat: true,
        startImmediately: true,
        defaultCurrency: 'USD',
        createdAt: now,
        updatedAt: now,
        ownerId: '24e2b5e4-3d38-4e57-89d8-2864813d18c0',
      },
      {
        id: uuidv4(),
        name: 'Dream Savers',
        description: 'Turn dreams into plans.',
        holder: 'admin',
        targetMemberCount: 8,
        contributionAmount: 50,
        payoutDay: 'friday',
        payoutOrder: 'first-come-first-serve',
        frequency: 'bi-weekly',
        isPublic: false,
        repeat: true,
        startImmediately: false,
        defaultCurrency: 'GBP',
        createdAt: now,
        updatedAt: now,
        ownerId: '3dc6d8aa-28fc-4ef6-8054-0db0ff67deab',
      },
      {
        id: uuidv4(),
        name: 'Golden Nest',
        description: 'Prepare for golden years.',
        holder: 'admin',
        targetMemberCount: 6,
        contributionAmount: 200,
        payoutDay: 'wednesday',
        payoutOrder: 'random',
        frequency: 'monthly',
        isPublic: true,
        repeat: false,
        startImmediately: true,
        defaultCurrency: 'KES',
        createdAt: now,
        updatedAt: now,
        ownerId: '6aff5e46-04e1-4cc6-b1bf-057354a4d605',
      },
      {
        id: uuidv4(),
        name: 'Bright Future Fund',
        description: 'Invest in tomorrow.',
        holder: 'member',
        targetMemberCount: 7,
        contributionAmount: 150,
        payoutDay: 'tuesday',
        payoutOrder: 'first-come-first-serve',
        frequency: 'weekly',
        isPublic: false,
        repeat: true,
        startImmediately: true,
        defaultCurrency: 'EUR',
        createdAt: now,
        updatedAt: now,
        ownerId: '9d7e6928-938d-4eff-8ba6-95b5d33ac271',
      },
      {
        id: uuidv4(),
        name: 'Fast Payouts',
        description: 'Quick rotation system.',
        holder: 'admin',
        targetMemberCount: 5,
        contributionAmount: 80,
        payoutDay: 'saturday',
        payoutOrder: 'random',
        frequency: 'daily',
        isPublic: true,
        repeat: true,
        startImmediately: false,
        defaultCurrency: 'NGN',
        createdAt: now,
        updatedAt: now,
        ownerId: 'abadf8e9-0b9e-411d-a20c-e005920c0407',
      },
      {
        id: uuidv4(),
        name: 'Prosper Circle',
        description: 'Grow together.',
        holder: 'admin',
        targetMemberCount: 12,
        contributionAmount: 120,
        payoutDay: 'sunday',
        payoutOrder: 'first-come-first-serve',
        frequency: 'monthly',
        isPublic: false,
        repeat: false,
        startImmediately: true,
        defaultCurrency: 'CNY',
        createdAt: now,
        updatedAt: now,
        ownerId: 'aeb8e454-42f9-47a8-8192-146ae4c16d28',
      },
      {
        id: uuidv4(),
        name: 'Rise Together',
        description: 'Support each other financially.',
        holder: 'admin',
        targetMemberCount: 9,
        contributionAmount: 90,
        payoutDay: 'thursday',
        payoutOrder: 'random',
        frequency: 'weekly',
        isPublic: true,
        repeat: true,
        startImmediately: false,
        defaultCurrency: 'INR',
        createdAt: now,
        updatedAt: now,
        ownerId: 'bafceb41-04a2-432c-97be-f38a26fe2ddb',
      },
      {
        id: uuidv4(),
        name: 'Momentum Loop',
        description: 'Cash flow made easy.',
        holder: 'admin',
        targetMemberCount: 6,
        contributionAmount: 60,
        payoutDay: 'friday',
        payoutOrder: 'first-come-first-serve',
        frequency: 'bi-weekly',
        isPublic: false,
        repeat: true,
        startImmediately: true,
        defaultCurrency: 'USD',
        createdAt: now,
        updatedAt: now,
        ownerId: 'bafceb41-04a2-432c-97be-f38a26fe2ddb',
      },
      {
        id: uuidv4(),
        name: 'Chama Network',
        description: 'Community-based funding.',
        holder: 'admin',
        targetMemberCount: 11,
        contributionAmount: 100,
        payoutDay: 'monday',
        payoutOrder: 'random',
        frequency: 'monthly',
        isPublic: true,
        repeat: true,
        startImmediately: true,
        defaultCurrency: 'KES',
        createdAt: now,
        updatedAt: now,
        ownerId: '6aff5e46-04e1-4cc6-b1bf-057354a4d605',
      },
      {
        id: uuidv4(),
        name: 'Aspire League',
        description: 'Fund your aspirations.',
        holder: 'admin',
        targetMemberCount: 8,
        contributionAmount: 75,
        payoutDay: 'tuesday',
        payoutOrder: 'first-come-first-serve',
        frequency: 'weekly',
        isPublic: false,
        repeat: true,
        startImmediately: false,
        defaultCurrency: 'GBP',
        createdAt: now,
        updatedAt: now,
        ownerId: '3dc6d8aa-28fc-4ef6-8054-0db0ff67deab',
      },
      {
        id: uuidv4(),
        name: 'Zen Circle',
        description: 'Minimalist saving style.',
        holder: 'member',
        targetMemberCount: 4,
        contributionAmount: 40,
        payoutDay: 'wednesday',
        payoutOrder: 'random',
        frequency: 'bi-weekly',
        isPublic: true,
        repeat: true,
        startImmediately: true,
        defaultCurrency: 'EUR',
        createdAt: now,
        updatedAt: now,
        ownerId: '3dc6d8aa-28fc-4ef6-8054-0db0ff67deab',
      },
      {
        id: uuidv4(),
        name: 'Wealth Club',
        description: 'Build lasting legacy.',
        holder: 'admin',
        targetMemberCount: 15,
        contributionAmount: 300,
        payoutDay: 'thursday',
        payoutOrder: 'first-come-first-serve',
        frequency: 'monthly',
        isPublic: false,
        repeat: false,
        startImmediately: false,
        defaultCurrency: 'USD',
        createdAt: now,
        updatedAt: now,
        ownerId: '3dc6d8aa-28fc-4ef6-8054-0db0ff67deab',
      },
      {
        id: uuidv4(),
        name: 'Circle Boost',
        description: 'Boost each other forward.',
        holder: 'admin',
        targetMemberCount: 9,
        contributionAmount: 90,
        payoutDay: 'friday',
        payoutOrder: 'random',
        frequency: 'weekly',
        isPublic: true,
        repeat: true,
        startImmediately: true,
        defaultCurrency: 'INR',
        createdAt: now,
        updatedAt: now,
        ownerId: 'c9f98204-a0e8-4488-87be-05538c5100e2',
      },
      {
        id: uuidv4(),
        name: 'Monthly Move',
        description: 'Structured monthly support.',
        holder: 'member',
        targetMemberCount: 10,
        contributionAmount: 130,
        payoutDay: 'monday',
        payoutOrder: 'first-come-first-serve',
        frequency: 'monthly',
        isPublic: false,
        repeat: false,
        startImmediately: true,
        defaultCurrency: 'NGN',
        createdAt: now,
        updatedAt: now,
        ownerId: 'f3ff623f-807d-4091-89bb-a535da9a7390',
      },
      {
        id: uuidv4(),
        name: 'Helping Hands',
        description: 'We lift each other.',
        holder: 'admin',
        targetMemberCount: 7,
        contributionAmount: 110,
        payoutDay: 'saturday',
        payoutOrder: 'random',
        frequency: 'weekly',
        isPublic: true,
        repeat: true,
        startImmediately: false,
        defaultCurrency: 'CNY',
        createdAt: now,
        updatedAt: now,
        ownerId: 'f3ff623f-807d-4091-89bb-a535da9a7390',
      },
    ];

    await queryInterface.bulkInsert('groups', groups, {});
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('groups', null, {});
  },
};
